### ISSUE TITLE
reprovision marketplace certs

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/betachannel#33]
Since builds aren't the most accessible, I would like to be able to restore my phone's functionality back to (or even in addition to) marketplace after modifying my certs.

**Comment by ozten** [comment]
Fixed in https://github.com/ozten/betafox-addon/tree/master/cli and 394df6d

The first time `provision-betafox.sh` is run, it is assumed the device has production certificates. These are backed up.

Providing new `revert-provisioning.sh` which uses this backup to restore production certs.

To test with existing BetaFox devices - sorry, please flash phones to revert. Next time will work, as these existing phones are missing the `backup` directory.
